# Generated by Django 2.1.3 on 2020-04-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='city',
        ),
    ]
