# Generated by Django 2.2.12 on 2020-05-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200422_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(),
        ),
    ]
