# Generated by Django 2.2.12 on 2020-06-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20200612_2112'),
        ('course', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='people.Teacher'),
            preserve_default=False,
        ),
    ]
