# Generated by Django 2.2.12 on 2020-06-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
