# Generated by Django 2.2.12 on 2020-06-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_remove_student_courses'),
        ('course', '0007_auto_20200612_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.City'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='people.Student'),
        ),
    ]
