# Generated by Django 2.2.12 on 2020-06-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_studentincources'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='members',
            field=models.ManyToManyField(through='course.StudentInCources', to='course.Course'),
        ),
    ]
