# Generated by Django 2.2.12 on 2020-06-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200619_1816'),
        ('people', '0005_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='course', to='course.Course'),
        ),
    ]
